server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wukong_rental?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 149779 # 请根据实际情况修改
    
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印 SQL
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto # 主键自增
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

jwt:
  secret: WukongRentalSecretKey1234567890wukongrentalsecretkey1234567890
  expiration: 86400000 # 24 小时
